### ISSUE TITLE
Anonymous user is able to visit recipe#new view

### ISSUE THREAD

**Issue by jpalmieri** [jpalmieri/brewery#3]
Steps to repro:
0) log out if necessary
1) visit root view
2) click "New Recipe

Observed behavior:
Anonymous user is able to view recipe#new
Upon form submission, app crashes

Intended behavior (version 1):
Anonymous user is redirected to root
Flash error notifies user that they must be logged in to create a new recipe

Intended behavior (alternate version):
When anonymous user initially visits root, "New recipe" link is not visible

**Comment by jpalmieri** [comment]
I think v.1 would be better because it baits the user into signing up. Thoughts?

**Comment by jpalmieri** [comment]
Or maybe this for intended behavior v.3:
Anonymous user is redirected to devise/sessions#new
Flash error notifies user that they must be logged in to create a new recipe

Then user can either sign in or create a new account. Seems like a better flow since it takes one step out of getting to recipe#new

**Comment by jpalmieri** [comment]
spec for v.3 https://github.com/jpalmieri/brewery/commit/31affcb4a0a33419e953b10aca7e103836fe3f7d

**Comment by jpalmieri** [comment]
I decided to use devise's `before_action :authenticate_user!` instead of Pundit, since it redirects to the `new_user_session` path; seems to be more elegant. I can add pundit later if needed.

**Comment by eliotsykes** [comment]
Agreed that v3 looks to be the best flow for users.

**Comment by jpalmieri** [comment]
Fixed in PR https://github.com/jpalmieri/brewery/pull/4
